// Generated by gencpp from file beginner_tutorials/MimsyIMURequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MIMSYIMUREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_MIMSYIMUREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct MimsyIMURequest_
{
  typedef MimsyIMURequest_<ContainerAllocator> Type;

  MimsyIMURequest_()
    : accelx(0)
    , mote_ip()  {
    }
  MimsyIMURequest_(const ContainerAllocator& _alloc)
    : accelx(0)
    , mote_ip(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _accelx_type;
  _accelx_type accelx;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mote_ip_type;
  _mote_ip_type mote_ip;




  typedef boost::shared_ptr< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> const> ConstPtr;

}; // struct MimsyIMURequest_

typedef ::beginner_tutorials::MimsyIMURequest_<std::allocator<void> > MimsyIMURequest;

typedef boost::shared_ptr< ::beginner_tutorials::MimsyIMURequest > MimsyIMURequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::MimsyIMURequest const> MimsyIMURequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/vagrant/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "060acebec8ee14dc450c3622112bf325";
  }

  static const char* value(const ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x060acebec8ee14dcULL;
  static const uint64_t static_value2 = 0x450c3622112bf325ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/MimsyIMURequest";
  }

  static const char* value(const ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 accelx\n\
string mote_ip\n\
";
  }

  static const char* value(const ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accelx);
      stream.next(m.mote_ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MimsyIMURequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::MimsyIMURequest_<ContainerAllocator>& v)
  {
    s << indent << "accelx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.accelx);
    s << indent << "mote_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mote_ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MIMSYIMUREQUEST_H
