// Generated by gencpp from file beginner_tutorials/MimsyIMU.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MIMSYIMU_H
#define BEGINNER_TUTORIALS_MESSAGE_MIMSYIMU_H

#include <ros/service_traits.h>


#include <beginner_tutorials/MimsyIMURequest.h>
#include <beginner_tutorials/MimsyIMUResponse.h>


namespace beginner_tutorials
{

struct MimsyIMU
{

typedef MimsyIMURequest Request;
typedef MimsyIMUResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MimsyIMU
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::MimsyIMU > {
  static const char* value()
  {
    return "c31e1566ea5c48673b33eed78f22421a";
  }

  static const char* value(const ::beginner_tutorials::MimsyIMU&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::MimsyIMU > {
  static const char* value()
  {
    return "beginner_tutorials/MimsyIMU";
  }

  static const char* value(const ::beginner_tutorials::MimsyIMU&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::MimsyIMURequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::MimsyIMU > 
template<>
struct MD5Sum< ::beginner_tutorials::MimsyIMURequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::MimsyIMU >::value();
  }
  static const char* value(const ::beginner_tutorials::MimsyIMURequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::MimsyIMURequest> should match 
// service_traits::DataType< ::beginner_tutorials::MimsyIMU > 
template<>
struct DataType< ::beginner_tutorials::MimsyIMURequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::MimsyIMU >::value();
  }
  static const char* value(const ::beginner_tutorials::MimsyIMURequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::MimsyIMUResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::MimsyIMU > 
template<>
struct MD5Sum< ::beginner_tutorials::MimsyIMUResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::MimsyIMU >::value();
  }
  static const char* value(const ::beginner_tutorials::MimsyIMUResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::MimsyIMUResponse> should match 
// service_traits::DataType< ::beginner_tutorials::MimsyIMU > 
template<>
struct DataType< ::beginner_tutorials::MimsyIMUResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::MimsyIMU >::value();
  }
  static const char* value(const ::beginner_tutorials::MimsyIMUResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MIMSYIMU_H
